config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homepage#index'
  get '/plant_tree', to: 'homepage#plant_tree'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end

  def plant_tree
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/index.html.erb
<div class="row tglip-top-header">
  <div class="col-xs-12 logo">
    <img src="<%= asset_path('tglipM.jpg') %>" />
  </div>
  <div class="col-xs-12 header-heading">
    <h1>5 Star Social initiative</h1>
  </div>
</div>

<div class="tglip-home container">
  <div class="tglip-tree-container">
    <div class="tree-image">
      <a href="<%= plant_tree_path %>">
        <img src="<%= asset_path('tglip-tree.png') %>" />
      </a>
    </div>
    <div class="tree-content bold">
      <p>Improve the environment by planting a tree with a click on the occassion of World Environment Day.</p>
    </div>
  </div>
  <div class="tglip-powered">
    <div class="tglip-powered-text bold">
      <h1>Powered By</h1>
    </div>
    <div class="tglip-powered-image">
      <img src="<%= asset_path('sankalp-taru-logo.png') %>" />
    </div>
  </div>
</div>

app/views/homepage/plant_tree.html.erb
<div class="inaugrate-campaign">
  <div class="inaugrate-msg">
    <p>Inaugurate the campaign with your pioneer tree.</p>
  </div>
  <div id="contact-form" class="person-details">
    <form id="contact" action="">
      <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" class="form-control" id="name" value="">
      </div>
      <div class="form-group">
        <label for="email">Email address:</label>
        <input type="email" class="form-control" id="email" value="">
      </div>
      <div class="form-group">
        <label for="pwd">Password:</label>
        <input type="password" class="form-control" id="pwd" value="">
      </div>
      <button type="submit" class="btn btn-default submit">Click Here</button>
    </form>
  </div>
  <div class="on-submit-show-message"><p id="message"></p></div>
  <%= link_to 'Back to Homepage Page', root_path, class:"link-to" %>
</div>

<script>
  function sendContactForm() {
    var name = document.getElementById('name').value;
    var email = document.getElementById('email').value;
    var text = "Thank you for planting a tree with us " + name + ' ' + 'your mail id is' + ' ' + email + '.' + '\n' +
                "Welcome to the 5 Star Social Initiative"
    $('.on-submit-show-message').fadeIn('fast');
    document.getElementById("message").innerHTML = text;
    setTimeout(function() {
      $('.on-submit-show-message').fadeOut('slow');
    }, 5000);
  }
  $('#contact').submit(function () {
    sendContactForm();
    return false;
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TGLIP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>